# Generated by Django 5.2.6 on 2025-09-19 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMudarLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now=True)),
                ('cabo', models.ManyToManyField(blank=True, to='inventory.cabo')),
                ('equipamento', models.ManyToManyField(blank=True, to='inventory.equipamento')),
                ('localfrom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logSaída', to='inventory.local')),
                ('localto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logEntrada', to='inventory.local')),
            ],
        ),
        migrations.CreateModel(
            name='LogSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('timeout', models.DateTimeField(auto_now=True)),
                ('timein', models.DateTimeField()),
                ('tempo', models.IntegerField()),
                ('cabo', models.ManyToManyField(blank=True, to='inventory.cabo')),
                ('equipamento', models.ManyToManyField(blank=True, to='inventory.equipamento')),
            ],
        ),
    ]
