# Generated by Django 5.2.6 on 2025-09-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsaida',
            name='timein',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
