# Generated by Django 5.2.6 on 2025-09-23 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_logsaida_timein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmudarlocal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logsaida',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
