# Generated by Django 5.2.6 on 2025-09-19 01:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('taken', 'Retirado'), ('inventory', 'Em Inventário')], default='inventory', max_length=10)),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cabos', to='inventory.local')),
            ],
        ),
        migrations.CreateModel(
            name='Cabo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('comprimento', models.IntegerField()),
                ('status', models.CharField(choices=[('taken', 'Retirado'), ('inventory', 'Em Inventário')], default='inventory', max_length=10)),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Equipamento', to='inventory.local')),
            ],
        ),
    ]
