# Generated by Django 5.2.6 on 2025-09-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabo',
            name='comprimento',
            field=models.IntegerField(),
        ),
    ]
