# Generated by Django 5.2.6 on 2025-09-17 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_local_equipamento_local_cabo_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabo',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Equipamento', to='inventory.local'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cabos', to='inventory.local'),
        ),
    ]
