# Generated by Django 5.2.6 on 2025-09-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_cabo_local_alter_equipamento_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='local',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
