# Generated by Django 5.2.6 on 2025-09-17 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_equipamento_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cabos', to='inventory.local'),
        ),
    ]
