# Generated by Django 5.2.6 on 2025-09-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_equipamento_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabo',
            name='status',
            field=models.CharField(choices=[('taken', 'Retirado'), ('inventory', 'Em Inventário')], default='inventory', max_length=10),
        ),
    ]
