# Generated by Django 5.2.6 on 2025-09-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_cabo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('taken', 'Retirado'), ('inventory', 'Em Inventário')], default='inventory', max_length=10),
        ),
    ]
