# Generated by Django 5.2.6 on 2025-09-16 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.DateTimeField(auto_now=True)),
                ('timein', models.DateTimeField()),
                ('nome', models.CharField(max_length=30)),
                ('tempo', models.IntegerField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.equipamento')),
            ],
        ),
    ]
